---
# tasks file for ansible-zimbra-single

- name: import zimbra10-ubuntu.yml
  import_tasks: zimbra10-ubuntu.yml
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "20.04"
  tags: zimbra10
