---
# tasks file for ansible-zimbra-single
- name: import centos.yml
  import_tasks: centos.yml
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "8"
  tags: install

- name: import ubuntu.yml
  import_tasks: ubuntu.yml
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "20.04"
  tags: install

- name: import zimbra9-centos.yml
  import_tasks: zimbra9-centos.yml
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "8"
  tags: zimbra9

- name: import zimbra9-ubuntu.yml
  import_tasks: zimbra9-ubuntu.yml
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "20.04"
  tags: zimbra9

- name: import zimbra10-ubuntu.yml
  import_tasks: zimbra10-ubuntu.yml
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "20.04"
  tags: zimbra10
